#!/bin/bash
# Guía rápida para instalar y gestionar servicios de Fuel Analytics

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║   🚀 FUEL ANALYTICS - SERVICIOS 24/7 PARA macOS                ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "📖 GUÍA RÁPIDA"
echo ""
echo "1️⃣  INSTALAR SERVICIOS (Primera vez)"
echo "   cd ~/Desktop/Fuel-Analytics-Backend/services"
echo "   bash install_services.sh"
echo ""
echo "2️⃣  VER ESTADO"
echo "   bash services/status_services.sh"
echo ""
echo "3️⃣  REINICIAR TODO"
echo "   bash services/restart_services.sh"
echo ""
echo "4️⃣  DETENER TODO"
echo "   bash services/stop_services.sh"
echo ""
echo "5️⃣  DESINSTALAR"
echo "   bash services/uninstall_services.sh"
echo ""
echo "6️⃣  VER LOGS EN TIEMPO REAL"
echo "   # Todos los logs:"
echo "   tail -f ~/Desktop/Fuel-Analytics-Backend/logs/*.log"
echo ""
echo "   # Solo backend:"
echo "   tail -f ~/Desktop/Fuel-Analytics-Backend/logs/backend.log"
echo ""
echo "   # Solo wialon:"
echo "   tail -f ~/Desktop/Fuel-Analytics-Backend/logs/wialon.log"
echo ""
echo "   # Solo frontend:"
echo "   tail -f ~/Desktop/Fuel-Analytics-Frontend/logs/frontend.log"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 COMANDOS ÚTILES DE LAUNCHCTL"
echo ""
echo "Ver servicios activos:"
echo "   launchctl list | grep fuelanalytics"
echo ""
echo "Iniciar un servicio:"
echo "   launchctl start com.fuelanalytics.backend"
echo "   launchctl start com.fuelanalytics.wialon"
echo "   launchctl start com.fuelanalytics.frontend"
echo ""
echo "Detener un servicio:"
echo "   launchctl stop com.fuelanalytics.backend"
echo ""
echo "Reiniciar un servicio (forzado):"
echo "   launchctl kickstart -k gui/\$UID/com.fuelanalytics.backend"
echo ""
echo "Ver información detallada:"
echo "   launchctl print gui/\$UID/com.fuelanalytics.backend"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 VERIFICACIÓN POST-INSTALACIÓN"
echo ""
echo "1. Backend API:  http://localhost:8000/docs"
echo "2. Frontend:     http://localhost:3000"
echo "3. Estado:       bash services/status_services.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
